name: legend_design
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animations: ^2.0.0
  provider: ^6.0.1
  lint: ^1.5.3
  flutter_highlight: ^0.7.0
  flutter_svg: ^1.1.0
  url_launcher: ^6.0.12
  antdesign_icons: ^0.0.3
  flutter_colorpicker: ^0.6.1
  google_fonts: ^2.1.0
  hooks_riverpod: ^2.1.1
  firebase_core: ^2.1.1
  firebase_database: ^10.0.3
  json_serializable: ^6.5.4
  legend_design_widgets:
    git:
      url: https://github.com/ThomasFercher/legend-widgets.git
  legend_design_core:
    git:
      url: https://github.com/ThomasFercher/legend-core.git
  legend_design_platform:
    git:
      url: https://github.com/ThomasFercher/legend-cross.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
  build_runner: ^2.3.2


flutter_icons:
  android: true
  ios: false
  windows: true
  image_path: "assets/photos/larrylegend_sm.png"

flutter:

  assets:
    - assets/
    - assets/flares/
    - assets/photos/

  uses-material-design: true