// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDazITb6Tw4bpeLJSO4D-KyCH4a0cBpmf0',
    appId: '1:363466733693:web:3c1eb44be6cf22b8a8d914',
    messagingSenderId: '363466733693',
    projectId: 'legenddocs-58eea',
    authDomain: 'legenddocs-58eea.firebaseapp.com',
    databaseURL: 'https://legenddocs-58eea-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'legenddocs-58eea.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgKWm3yAI7Tl5RqRFX8a9BL946n9ZY_CM',
    appId: '1:363466733693:android:24c539ab001b6545a8d914',
    messagingSenderId: '363466733693',
    projectId: 'legenddocs-58eea',
    databaseURL: 'https://legenddocs-58eea-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'legenddocs-58eea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9fOM1i9j-F5RC2Dyuib3_ixhdx86CRD8',
    appId: '1:363466733693:ios:1552f14b17621dd1a8d914',
    messagingSenderId: '363466733693',
    projectId: 'legenddocs-58eea',
    databaseURL: 'https://legenddocs-58eea-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'legenddocs-58eea.appspot.com',
    iosClientId: '363466733693-sv9hfivf3e7hk4p3fkara8riad621tl2.apps.googleusercontent.com',
    iosBundleId: 'com.legend.legendDesign',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9fOM1i9j-F5RC2Dyuib3_ixhdx86CRD8',
    appId: '1:363466733693:ios:c8bd5c5bdc4f7190a8d914',
    messagingSenderId: '363466733693',
    projectId: 'legenddocs-58eea',
    databaseURL: 'https://legenddocs-58eea-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'legenddocs-58eea.appspot.com',
    iosClientId: '363466733693-ach3ggd7gob0siqh5sbivkm4a7aoepj6.apps.googleusercontent.com',
    iosBundleId: 'com.legend.design.legendDesign',
  );
}
