
# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the workflow will run
on:
  
  push:
    branches: 
      - main 
  pull_request:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-18.04
    steps:
    # Set up Flutter.
    - name: Clone Flutter repository with master channel
      uses: subosito/flutter-action@4389e6cbc6cb8a4b18c628ff96ff90be0e926aa8
      with:
        channel: master
    #- run: flutter doctor -v

    # Checkout gallery code and get packages.
    - name: Checkout Legend code
      uses: actions/checkout@v2
    - run: flutter pub get

    # Build and deploy (by default, to staging).
    - run: flutter build -v web --release

    - name: Pushes to another repository
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB_REPO }}
      with:
        source-directory: 'build/web'
        destination-github-username: 'ThomasFercher'
        destination-repository-name: 'ThomasFercher.github.io'
        user-email: thomas.fercher@outlook.com
        target-branch: master

 
        
